### PR TITLE
bug 1597334: enable docker-layer-caching

### PR DESCRIPTION
**Pull request by willkg**
This enables docker-layer-caching to reduce build times in Circle CI.

### CODE REVIEW

**Comment by willkg** [comment]
First CI run passed in 13:32:

https://circleci.com/gh/mozilla-services/socorro/4975

The `Setup a remote Docker engine` step doesn't indicate that docker-layer-caching is enabled. I'm going to tweak the README and then push that as a commit and see if that uses the layer cache.

**Comment by willkg** [comment]
Second CI run used layer caches and passed in 4:41:

https://circleci.com/gh/mozilla-services/socorro/4976

The "build docker images" step took 32s.

I like this.

@sciurus, @jwhitlock: Does this look ok to you two?

**Comment by jwhitlock** [comment]
I [mentioned on the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1597334#c3) that we may want to remove the apt caches, which may make it more likely that there will be no file system changes and Docker will use the cache for later layers. This test suggests it doesn't matter. It could also be tricky to get that right with the `vim` install in a later step.

**Comment by willkg** [comment]
The `Dockerfile` was one of the first ones I wrote and it's likely junky in parts. If you wanted to spend some time streamlining it, that'd be super. Less complexity, less back-and-forth between bash, smaller image size, fewer steps, better cacheability--all those things are valuable. We can then build a better set of conventions and use that across all our projects.

**Comment by willkg** [comment]
Thank you!

**Pull request merged**
