### PR TITLE
Fix bug 1470707.  Remove e2e-tests from Socorro.

### PR DESCRIPTION
**Pull request by stephendonner**
@Osmose r?

https://www.youtube.com/watch?v=xQ9_vCTrxJM

### CODE REVIEW

**Comment by stephendonner** [comment]
@willkg thanks!  re: README, did you mean something other than https://github.com/mozilla-services/socorro/pull/4498/files#diff-355152bba9e4bab2bb2be02dd6f0aba1 ?

**Comment by willkg** [comment]
@stephendonner Yes. You need to remove this file:

https://github.com/mozilla-services/socorro/blob/master/docs/tests/e2e_readme.rst

**Comment by willkg** [comment]
@stephendonner If you run `make docs`, then you get this error:

```
$ make docs
./docker/as_me.sh --container docs ./docker/run_build_docs.sh
cp ../e2e-tests/README.md tests/e2e_readme.md
cp: cannot stat ‘../e2e-tests/README.md’: No such file or directory
Makefile:23: recipe for target 'html' failed
make: *** [html] Error 1
Makefile:35: recipe for target 'docs' failed
make: *** [docs] Error 2
```

Can you fix that, too, please?

**Comment by stephendonner** [comment]
🎉

**Pull request merged**
