### PR TITLE
Update and clean up some getting started docs

### PR DESCRIPTION
**Pull request by willkg**
I made some changes based on Jonathan's suggestions. The big issue was that the
documentation about running "make dockerupdatedata" was after the link sending
you off to the webapp documentation, so he missed it. This fixes that flow and
adds some more details which are probably helpful to know.

### CODE REVIEW

**Comment by willkg** [comment]
@lonnen I'm tagging you to review this figuring you haven't done much docker stuff with Socorro, so your eyes are newer.

I kind of hate the make rule names. We'll get rid of the "docker" prefix once I ditch vagrant and we can ditch some other things. "build" is a common rule name--and I think that one is fine". "setup" and "updatedata" seem vague and unhelpful.

What do you think about Getting Started? Does it flow well? At the end of it, do you feel like you understand enough of what happened and what you now have to do work?

What do you think about the make rule names?

**Comment by willkg** [comment]
Just to reign this in a bit, the goal for this PR is "make things a bit better" and "identify other things we can do to improve the docs without turning them into an omnibus, but defer the non-trivial ones to a later pass".

**Comment by lonnen** [comment]
Had to install the docker app on OSX and run that. Once I had that down, this was smooth sailing. `make dockerupdatedata` takes a few minutes but that's alright. 

Once I got things running I tried to set up the webapp and had some trouble. It may be beyond the scope here.

1. the compose script outputs `Starting development server at http://0.0.0.0:8000/` but `0.0.0.0` is not an allowed host and you should instead use `localhost`
2. `http://localhost:8000/_debug_login/` is referenced in the docs but in this setup complains that it cannot write or read from memcached.
3. even with updated data tools, the homepage graph does not load and trying to load topcrashers returns a BadArgument 500

Are those out of scope of this change?

**Comment by willkg** [comment]
This is helpful. I'll tweak the docker install section.

Django is saying "starting development server at http://0.0.0.0:8000". That sets it up to listen to all the available ip address. Port 8000 is exported from the container so that's the only one you can access from the host. Thus the message doesn't line up with the address you actually need to connect to. I'm not really sure what we can do about that. It's a problem any project running Django, Jinja2, etc has when used with Docker. Maybe other people have ideas about how to reduce that papercut.

The webapp docs definitely need to be updated. That's a project for a different day. The same can be said for pretty much everything outside of the gettingstarted.rst file.

I'm pretty sure item 3 is an issue because there isn't any crash data. @peterbe was suggesting we might want to fix the homepage such that it works in "no data" scenarios. That's an option. Once I get more processor stuff done, then we can populate the system with crashes and that'd be an additional step. Might be easiest to prime the system with a single "initial crash". I'll toss that in my list of things to think about.

**Comment by willkg** [comment]
I tweaked the getting started tools installation section. I think that's good enough to land this PR.

**Comment by willkg** [comment]
Thank you!

**Pull request merged**
