### PR TITLE
Add Mozilla Code of Conduct

### PR DESCRIPTION
**Pull request by Mozilla-GitHub-Standards**
As of January 1 2019, Mozilla requires that all GitHub projects include this [CODE_OF_CONDUCT.md](https://github.com/mozilla/repo-templates/blob/master/templates/CODE_OF_CONDUCT.md) file in the project root. The file has two parts:

1. Required Text - All text under the headings *Community Participation Guidelines and How to Report*, are required, and should not be altered.
2. Optional Text - The Project Specific Etiquette heading provides a space to speak more specifically about ways people can work effectively and inclusively together. Some examples of those can be found on the [Firefox Debugger](https://github.com/devtools-html/debugger.html/blob/master/CODE_OF_CONDUCT.md) project, and [Common Voice](https://github.com/mozilla/voice-web/blob/master/CODE_OF_CONDUCT.md). (The optional part is commented out in the [raw template file](https://raw.githubusercontent.com/mozilla/repo-templates/blob/master/templates/CODE_OF_CONDUCT.md), and will not be visible until you modify and uncomment that part.)

If you have any questions about this file, or Code of Conduct policies and procedures, please reach out to Mozilla-GitHub-Standards+CoC@mozilla.com.

_(Message COC002)_

### CODE REVIEW

**Comment by willkg** [comment]
We've already got one: https://github.com/mozilla-services/socorro/blob/master/CODE_OF_CONDUCT.rst

Thank you!

**Comment by Mozilla-GitHub-Standards** [comment]
Will,

FYI, you'll get nagged every time you rerun, as the official version is in 
markdown. If you don't have a strong reason for keeping as 
reStructuredText, please consider going with the markdown version.

--Hal

**Comment by willkg** [comment]
That's kind of frustrating and unfortunate.

**Comment by hwine** [comment]
@willkg - actually, I take it back. You'll need to change. The ``.rst`` format is not supported by the GitHub workflow around CoC documents. They don't register in the "Insights Community" display.

**Comment by willkg** [comment]
That surprises me since GitHub supports non-.md formats for other files also in that list and there are lots of other projects on GitHub that have .rst files.

If projects are using .rst and Sphinx for documentation, it's easy to include .rst files elsewhere in the repository using the `.. INCLUDE::` directive. Then it gets parsed and included in the docs. That's much harder when the file is .md. I really think we should be including these files in our docs. It's not sufficient to have them buried in the repo.

I'll look into it and if it turns out they really don't support `CODE_OF_CONDUCT.rst`, I'll contact GitHub and ask for support.

**Comment by willkg** [comment]
So, it looks like it doesn't have to do with the .rst format but rather that the file is not one of the ones GitHub recognizes.

django-badger has the CODE_OF_CONDUCT.md file, but it's also listed as not having one in the insights page:

* https://github.com/mozilla/django-badger/blob/master/CODE_OF_CONDUCT.md
* https://github.com/mozilla/django-badger/community

Here's the most recent thing I found about that:

https://github.community/t5/How-to-use-Git-and-GitHub/Code-of-Conduct-is-present-in-repo-but-Insights-gt-Community-tab/m-p/15496?advanced=false&collapse_discussion=true&q=CODE_OF_CONDUCT.rst&search_type=thread

If showing up in the insights tab is important, maybe we should use one of the ones they support? Maybe we should contact them and get ours added?

**Comment by hwine** [comment]
@willkg that discussion should happen with mozilla-github-standards@m.c -- those folks would be the ones to take any such action or change policy.

**Comment by emmairwin** [comment]
So, it looks like it doesn't have to do with the .rst format but rather that the file is not one of the ones GitHub recognizes.

Right.

And  to make maintenance sustainable in future.

**Comment by g-k** [comment]
@willkg @hwine can you CC me on the thread w/ moz-gh-stds or point me to any public discussions? 

My understanding is there are two issues:

- [ ] teach the moz-gh-stds bot to recognize CoC `.rst` files (and ideally provide a template/suggest updates to existing CoC.rst files; implementation-wise pandoc can probably convert `.md` to `.rst`)

- [ ] as @emmairwin points out, work with github to recognize the Mozilla CoC (ideally both `.md` and `.rst` formats) and display it on community insights pages (i.e. by replying in the thread @willkg mentioned). @hwine pointed out that this work should go through moz-gh-stds@

The benefit of `.rst` support is that the CoC can be included in other docs and e.g. published in the contributing section of a repo on https://readthedocs.org/ and not require another doc format for Python projects.

**Comment by g-k** [comment]
@hwine pointed me to the CoC bot script at: https://github.com/mozilla/github-org-scripts/blob/master/check_CoC.py

**Comment by hwine** [comment]
@g-k fyi, script moved to https://github.com/mozilla/Mozilla-GitHub-Standards/

**Comment by willkg** [comment]
Reopening to land this.

**Comment by willkg** [comment]
On second thought--I'm going to cherry-pick the commit and start a new branch and PR.

**Comment by She433** [comment]
Nothing here error 404 just doesn't exist . Bug is this whomever was doing this in the json venerability files had a habit of not wanting to leave a trace . Erased files , contributors or whomever could figure out what they were doing.

**Comment by She433** [comment]
githubuser.com is what someone does. Never used https or anything and is only trying to find accounts that are worth harming others financially etc

**Pull request closed without merging**
