### PR TITLE
Bug 1798480 - Ignore guard_dispatch_icall_nop when generating a crash signature

### PR DESCRIPTION
**Pull request by gabrielesvelto**

### CODE REVIEW

**Review by willkg — APPROVED** [review]
```
Crash id: 5742bc56-1ead-4ddd-8f6d-90c7d0221031
Original: guard_dispatch_icall_nop
New:      ArSymbol::SetName
Same?:    False
```

I also see a lot of crash reports with signature `_guard_dispatch_icall_nop`. Do we want to add that to the irrelevant list, too?

https://crash-stats.mozilla.org/search/?signature=~_guard_dispatch_icall_nop&date=%3E%3D2022-10-25T15%3A19%3A00.000Z&date=%3C2022-11-01T15%3A19%3A00.000Z&_facets=signature&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#crash-reports

**Comment by willkg** [comment]
@gabrielesvelto ^^^

**Comment by gabrielesvelto** [comment]
Yes, definitely, nice catch!

**Comment by willkg** [comment]
I added the `_guard_dispatch_icall_nop` to the irrelevant list and rebased on main tip.

```
app@socorro:/app$ socorro-cmd fetch_crashids --signature='_guard_dispatch_icall_nop' --num=1 | socorro-cmd signature
Crash id: c8f1ef6b-d4e3-4288-a18a-3eeb70221101
Original: _guard_dispatch_icall_nop
New:      mio::sys::windows::selector::SelectorInner::feed_events
Same?:    False
```

**Comment by willkg** [comment]
Thank you!

**Pull request merged**
