### PR TITLE
Add rust oom signature

### PR DESCRIPTION
**Pull request by jdm**
It would be nice to add `core::result::unwrap_failed<hashglobe::FailedAllocationError>`, but it apparently is transformed in the signature into a generic `unwrap_failed<T>` per https://crash-stats.mozilla.com/report/index/d54a2975-9c55-4567-a92f-c755c0170903 :/

### CODE REVIEW

**Comment by willkg** [comment]
Is there a Bugzilla bug related to this change? If not, can we write one up so we can associate this?

**Comment by willkg** [comment]
Oops--I see the bug now. Sorry about that!

**Comment by willkg** [comment]
Oh, my bad. That bug isn't a Socorro but. Can you open up a Socorro bug for this change? Then we can associate this PR with that bug and move forward.

**Comment by willkg** [comment]
@jdm Can you write up a Socorro bug for this change?

**Comment by willkg** [comment]
@jdm With this change, the signature for the example crash didn't change at all:

```
app@3fd1310168d2:/app$ python -m socorro.signature d54a2975-9c55-4567-a92f-c755c0170903
Original: core::result::unwrap_failed<T> | hashglobe::hash_map::HashMap<T>::entry<T>
New:      core::result::unwrap_failed<T> | hashglobe::hash_map::HashMap<T>::entry<T>
Same?:    True
```

Is the signature for the crash in the PR description supposed to change? If not, are there other example crashes we can test?

**Comment by jdm** [comment]
This is supposed to mark the crash report as an OOM, not modify the signature. This change is based on https://crash-stats.mozilla.com/report/index/cb3e453d-5135-4b57-8d9a-656330170820.

**Comment by jdm** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1399513.

**Comment by jdm** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1399515 for the unrelated comment I originally made.

**Comment by willkg** [comment]
Using the cb3e453d-5135-4b57-8d9a-656330170820 crash:

```
app@2e8a1040c15d:/app$ python -m socorro.signature cb3e453d-5135-4b57-8d9a-656330170820
Original: alloc::oom::oom | std::collections::hash::map::HashMap<T>::resize<T> | std::collections::hash::map::HashMap<T>::entry<T> | style::selector_map::SelectorMap<T>::insert<T>
New:      OOM | unknown | alloc::oom::oom | std::collections::hash::map::HashMap<T>::resize<T> | std::collections::hash::map::HashMap<T>::entry<T> | style::selector_map::SelectorMap<T>::insert<T>
Same?:    False
```

Is that the kind of change you're expecting with this PR?

**Comment by jdm** [comment]
Yes.

**Comment by willkg** [comment]
Thank you!

**Pull request merged**
