### PR TITLE
fixes bug 1399732 - std::_Hash<T>

### PR DESCRIPTION
**Pull request by willkg**
Signature generation output after this change:

```
app@f6825c359570:/app$ python -m socorro.signature 9086ef0f-a892-405f-9fce-89e6d0170914 c2e8ca35-1779-4e95-aa7b-45ad60170913 5b075f26-9c87-4421-8a55-995730170914 2a1937d1-00ec-4ec3-b131-353b50170914 0b29cecd-fbd4-4287-8c8f-bf7c80170913
Crash id: 9086ef0f-a892-405f-9fce-89e6d0170914
Original: std::_Hash<T>::equal_range
New:      std::_Hash<T>::equal_range | mozilla::gfx::DrawEventRecorderPrivate::RemoveStoredObject
Same?:    False
Crash id: c2e8ca35-1779-4e95-aa7b-45ad60170913
Original: std::_Hash<T>::_End
New:      std::_Hash<T>::_End | std::_Hash<T>::equal_range | mozilla::gfx::DrawEventRecorderPrivate::RemoveStoredObject
Same?:    False
Crash id: 5b075f26-9c87-4421-8a55-995730170914
Original: std::_Hash<T>::_End
New:      std::_Hash<T>::_End | std::_Hash<T>::_Insert<T> | mozilla::gfx::DrawTargetD2D1::AddDependencyOnSource
Same?:    False
Crash id: 2a1937d1-00ec-4ec3-b131-353b50170914
Original: std::_Hash<T>::_Insert<T>
New:      std::_Hash<T>::_Insert<T> | stdext::hash_map<T>::operator[]
Same?:    False
Crash id: 0b29cecd-fbd4-4287-8c8f-bf7c80170913
Original: std::_Hash<T>::lower_bound
New:      std::_Hash<T>::lower_bound | CDevice::CreateBlendState_Worker
Same?:    False
```

### CODE REVIEW

**Comment by willkg** [comment]
@nnethercote Do the new signatures look like what you expect?

**Comment by nnethercote** [comment]
They look good, thank you.

But the 4th example you showed indicates there is another, similar regex that would help even more:

> stdext::hash_map<T>::.*

**Comment by willkg** [comment]
Ok. I'm going to land this as is and look into `stdext::hash_map::.*` as a separate PR.

**Comment by nnethercote** [comment]
Actually, it should be this: `stdext::hash_map<T>::.*`

(I'm not sure if I forgot the `<T>` or if the Markdown processor somehow swallowed it.)

**Pull request merged**
