### PR TITLE
Update fennec versions

### PR DESCRIPTION
**Pull request by jcristau**
Bump release to 68.7.0, and remove beta due to the migration to fenix

### CODE REVIEW

**Comment by willkg** [comment]
The tests failed because the localstack-sqs service didn't start. That's covered in bug 1624403.

I restarted the tests.

**Comment by willkg** [comment]
@rvandermeulen Does this look ok to you? You often update the versions for Fennec, so I'm tagging you for review.

**Comment by rvandermeulen** [comment]
Yes, looks good to me!

**Comment by willkg** [comment]
Thank you!

**Pull request merged**
