### PR TITLE
fixes bug 1434678 - add message about rates to crashes-per-day graph

### PR DESCRIPTION
**Pull request by willkg**
This adds a message about rates to the crashes-per-day graph with a link to Mission Control which has better crash rate data.

This also deletes some dead code.

### CODE REVIEW

**Comment by willkg** [comment]
@lonnen I'm tagging you to review this because it's mostly a text change. Is the text helpful?

**Comment by willkg** [comment]
One thing we probably want is a bug to update the mission control link to a "more prod-like link" when one exists. I'll do that after this lands.

**Comment by wlach** [comment]
Text/link lgtm.

**Comment by willkg** [comment]
I accidentally dropped my pen and I turned to pick it up and when I turned back, there was a note on my keyboard from @lonnen conveying his approval and instructing me to merge this.

I'm not sure how that note got into my office, but I'll merge this now.

**Pull request merged**
