### PR TITLE
Update Firefox to 59.0 in Sauce Labs

### PR DESCRIPTION
**Pull request by stephendonner**
Passing ad-hoc here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/socorro.adhoc/164/console

xref: https://bugzilla.mozilla.org/show_bug.cgi?id=1445782

### CODE REVIEW

**Comment by stephendonner** [comment]
@chartjes @willkg @Osmose r?

**Comment by karlht** [comment]
Rebase this, please?

**Comment by stephendonner** [comment]
@karlht done!

**Comment by stephendonner** [comment]
And one more, to accommodate https://github.com/mozilla-services/socorro/commit/cb0a5515fecb9e1c12df38e7d1036a4bb414338f

**Pull request merged**
