### PR TITLE
WIP: incremental progress towards bug 1469718

### PR DESCRIPTION
**Pull request by lonnen**
This PR contains incremental progress towards bug 1469718. The commit log breaks down each little fix.

It's a littler scattershot since I work on this without internet access and can't file new or map to existing bugs. I intended to do that when I reconnected but it's taken me so long to come back around on it that I'm offering it as-is.

### CODE REVIEW

**Comment by willkg** [comment]
This looks awesome!

@lonnen Were you thinking I should take this, update it, and then get it landed?

**Comment by lonnen** [comment]
@willkg please, if you'd like. Updates have been no-conflict so far.

**Comment by willkg** [comment]
^^^ That rebases against master tip. It also adds a commit that fixes `socorro/lib/cache.py` and its tests and fixes a couple of other things that I noticed in the PR.

@lonnen Passing this back to you to continue working on!

**Comment by willkg** [comment]
^^^ That rebases against master tip. I cherry-picked the changes to `Makefile` and landed them with some other minor changes. I figured I'd do that now because those changes are going to intersect with the changes I'm making to unify all the docker images. That'll reduce the bitrot in this PR.

**Comment by willkg** [comment]
I talked to @lonnen. I'm concerned about bitrot, so I'm going to finish this up and land it now. Further python 3 work will be done in a new PR.

**Pull request merged**
