### PR TITLE
bug 1665791: add mozilla::UniquePtr<T>::reset to the prefix list

### PR DESCRIPTION
**Pull request by jcristau**

### CODE REVIEW

**Comment by willkg** [comment]
```
app@socorro:/app$ socorro-cmd signature 7e93bb78-657c-47d1-8925-998190200916
Crash id: 7e93bb78-657c-47d1-8925-998190200916
Original: mozilla::UniquePtr<T>::reset
New:      mozilla::UniquePtr<T>::reset | mozilla::net::HttpBaseChannel::~HttpBaseChannel
Same?:    False
```

**Review by willkg — APPROVED** [review]
Looks good! Thank you!

**Comment by willkg** [comment]
Oops--I messed up the branch. I thought "Update" would rebase and not merge main to this branch.

@jcristau Can you rebase this against main? If that's too annoying, I can create a new PR. Sorry!

**Comment by jcristau** [comment]
Rebased and force-pushed.

**Comment by willkg** [comment]
You rock--thank you!

**Review by willkg — APPROVED** [review]

**Pull request merged**
