### PR TITLE
Upgrade to Firefox 56

### PR DESCRIPTION
**Pull request by stephendonner**
@chartjes r?

Ad-hoc passing here: https://gist.github.com/stephendonner/51c33acf3e5a01d05520bbda1e6c8fa4

### CODE REVIEW

**Comment by stephendonner** [comment]
@Osmose / @willkg r?

**Comment by willkg** [comment]
Oh, right. I think @chartjes is out. I'll look into it.

**Comment by chartjes** [comment]
Sorry, feeling sick today. Looks good to me.

**Comment by stephendonner** [comment]
Thanks, everyone!

**Pull request merged**
