### PR TITLE
Upgrade to Firefox-59.0

### PR DESCRIPTION
**Pull request by stephendonner**
This addresses https://bugzilla.mozilla.org/show_bug.cgi?id=1445561

Full Docker build and run, here (with better results than current master, I might add): https://gist.github.com/stephendonner/f42e31f986ab68f4f591c99a5588d8e1

### CODE REVIEW

**Comment by stephendonner** [comment]
@chartjes r? when updated to master, and passing?

**Comment by karlht** [comment]
What needs to be done to get this to pass CircleCI?

**Comment by stephendonner** [comment]
This just needs clicking "update branch" to rebase w/master, which I've just-now done; assuming that'll pass, should be good to merge, but we should check with @willkg (probably best to let him merge)

**Comment by willkg** [comment]
I'm ok with other people merging. I figure if they have the commit bit, that's fine by me. :+1:

**Pull request merged**
