### PR TITLE
fixes bug 794524 - drop plugins_report table

### PR DESCRIPTION
**Pull request by peterbe**
When I started working on this, I discovered that it appears that we're still actively writing to these tables. I can't find any reference to it ever being queried. Which kinda makes sense since it used to be used by the search we had before we had super search. 

So I'm going to be careful and first make a PR that deprecates the writes. Then we'll let that go into stage and check that all is well with the world.

### CODE REVIEW

**Comment by peterbe** [comment]
Here's the PR that this depends on 
https://github.com/mozilla-services/socorro/pull/3970
Technically it doesn't because codewise they're disjoint but it doesn't make sense to drop a table when you still have SQL insert statements in the Python code.

**Comment by peterbe** [comment]
Travis is failing right now. That'll get taken care of once https://github.com/mozilla-services/socorro/pull/3970 lands and we rebase up this one.

**Comment by willkg** [comment]
I vote we wait until Monday to work on this further. That gives -stage some time to be happy/sad about `plugins_report` changes in PR #3970.

Does that sound ok?

**Comment by peterbe** [comment]
> Does that sound ok?

Totally. No rush. Also, it's 3pm on a Friday.

**Pull request merged**
