### PR TITLE
bug 1397863 - Add WrapNotNull to the prefix list

### PR DESCRIPTION
**Pull request by aosmond**

### CODE REVIEW

**Comment by willkg** [comment]
Is there a bug for this? Plus one or more crash reports that show the problem?

**Comment by aosmond** [comment]
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1397235
Example crash report: https://crash-stats.mozilla.com/report/index/7a5ef2f8-663d-4f54-a1f3-b83570170907#tab-details

**Comment by willkg** [comment]
@aosmond Can you write up a bug that covers making this change to Socorro with links to the relevant crash reports? Something like this one: https://bugzilla.mozilla.org/show_bug.cgi?id=1396928

**Comment by aosmond** [comment]
Ah sorry, I was looking at a really old PR that didn't have a bug attached :).
See bug 1397863 (https://bugzilla.mozilla.org/show_bug.cgi?id=1397863)

**Comment by willkg** [comment]
I really appreciate that! Thank you!

I just ran this through the new signature generation command line interface:

```
app@1d93bb8029f3:/app$ python -m socorro.signature -v 7a5ef2f8-663d-4f54-a1f3-b83570170907
Original: mozilla::WrapNotNull<T>
New:      mozilla::WrapNotNull<T> | mozilla::image::ImageSurfaceCache::SuggestedSize
Same?:    False
Notes:    (2)
          SignatureGenerationRule:  -> mozilla::WrapNotNull<T> | mozilla::image::ImageSurfaceCache::SuggestedSize
          SigTrim: mozilla::WrapNotNull<T> | mozilla::image::ImageSurfaceCache::SuggestedSize -> mozilla::WrapNotNull<T> | mozilla::image::ImageSurfaceCache::SuggestedSize
```

Does that look good?

**Comment by willkg** [comment]
@aosmond ^^^

**Comment by aosmond** [comment]
Yup, looks good!

**Pull request merged**
