### PR TITLE
Add example of using shell scripts for processing crashes

### PR DESCRIPTION
**Pull request by willkg**
I didn't actually test this, but pretty sure this is correct.

Can you test this out? Is it clear what's going on and how the pieces work with each other?

### CODE REVIEW

**Comment by Osmose** [comment]
I ran the steps locally and got this output when I finally ran the processor: https://gist.github.com/Osmose/1aa91bf76ee9e6fda0e8f8958ffa352c

I'm not entirely sure how to parse that. After running it, my webapp now hangs indefinitely when I try to load a page.

**Comment by Osmose** [comment]
I ran this locally again on different Wifi, and I think it worked. I see some entries in my top crashers list, and have some individual crash data I can look at. However, the front page of my webapp shows an error message still:

screen shot 2017-10-13 at 12 12 30

Is this something to worry about? If not, then I'll approve this PR.

**Comment by willkg** [comment]
Yeah... So I talked with @peterbe about this a bit and I forget the specifics, but that warning shows up if there's not enough data or some kind of data is missing or something like that.

It'd be good to figure out "what do I need to do to get the front page to work". Maybe we should codify that in this example. It might be something like "1000 crashes" or "100+ crashes for the last few days" or something like that.

We could experiment with that as part of this PR, but I'm inclined to land this as is and write up a bug for figuring that out. It'd definitely be helpful to know when doing webapp work.

**Comment by peterbe** [comment]
For what it's worth, I don't think it's a matter of if you need 100 or 1,000 datapoints. I think you basically need 1.

But isn't that error because there's no data in the weekly indexes? I.e. the socorroYYYYWW doesn't exist.

**Comment by willkg** [comment]
@peterbe Indexes get created automatically when crashes are processed, so if we're pulling 100 firefox crashes from yesterday, than the week should be created.

Is there a crontabber job that needs to run?

**Comment by peterbe** [comment]
@willkg Sorry for sounding lazy but I'm not sure what condition causes that red alert to appear. Best to track it down in the code with some print statements. 

PS. If it's not a missing index, it could also be that ES isn't successful on every shard.

**Comment by willkg** [comment]
@Osmose What you're seeing is not unexpected. I created bug 1408536 to figure out the product home page. We can do that work there. I think everything else here is good to go.

**Comment by willkg** [comment]
Thank you!

**Pull request merged**
