### PR TITLE
fix bug 1541474: add real_drop_in_place to prefix list

### PR DESCRIPTION
**Pull request by staktrace**
real_drop_in_place is part of rust's libcore, so just having that in the
crash signature results in conflating different crash stacks. Adding it
to the prefix list gets us the caller frame which allows us to
distinguish between the different callers.

### CODE REVIEW

**Comment by willkg** [comment]
Does this look good to you?

```
app@537f099ed0d5:/app$ socorro-cmd fetch_crashids --signature-contains=real_drop_in_place --num=5 | socorro-cmd signature
Crash id: d9291a0a-6061-4c9f-aac7-885d10190403
Original: core::ptr::real_drop_in_place<T>
New:      core::ptr::real_drop_in_place<T> | core::ptr::real_drop_in_place<T> | core::ptr::real_drop_in_place<T> | geckoservo::glue::Servo_StyleSet_Drop
Same?:    False

Crash id: 8c800317-8a94-4cc3-acaa-975810190403
Original: core::ptr::real_drop_in_place<T>
New:      core::ptr::real_drop_in_place<T> | style::selector_map::MaybeCaseInsensitiveHashMap<T>::clear<T>
Same?:    False

Crash id: 16c8b4b0-5d22-4dad-a812-1a6d50190403
Original: core::ptr::real_drop_in_place<T>
New:      core::ptr::real_drop_in_place<T> | core::ptr::real_drop_in_place<T> | core::ptr::real_drop_in_place<T> | geckoservo::glue::Servo_StyleSet_Drop
Same?:    False

Crash id: 5e81737c-7486-4c7b-9506-202ff0190403
Original: core::ptr::real_drop_in_place<T>
New:      core::ptr::real_drop_in_place<T> | core::ptr::real_drop_in_place<T> | core::ptr::real_drop_in_place<T> | geckoservo::glue::Servo_StyleSet_Drop
Same?:    False

Crash id: 94b99725-8ce7-490b-b5e3-0bf5e0190403
Original: core::ptr::real_drop_in_place<T>
New:      core::ptr::real_drop_in_place<T> | servo_arc::Arc<T>::drop_slow<T>
Same?:    False
```

**Comment by staktrace** [comment]
The duplicated `core::ptr::real_drop_in_place` frames aren't ideal but it's good enough to distinguish the crashes, so in that sense it's fine by me. if we can deduplicate those frames that would be one step better.

**Comment by willkg** [comment]
Oh, funky. I thought they weren't *exact* duplicates, but they totally are. I thought there was code to remove that. I'll land this now and then look into that next.

**Comment by willkg** [comment]
Thank you!

**Pull request merged**
