### PR TITLE
fixes bug 1377758 - no thunderbird aurora version featured

### PR DESCRIPTION
**Pull request by peterbe**

### CODE REVIEW

**Comment by willkg** [comment]
This seems fine to me. r+

**Comment by peterbe** [comment]
Note-to-self; Going to wait for Wayne to weigh in.

**Comment by peterbe** [comment]
This is going to require an upgrade of the admin nodes once this goes to production. So we should see the effect late next week. I.e. Aug 10.

**Comment by willkg** [comment]
@peterbe Next week is a release week, so we're not doing a -prod deployment on August 10th.

**Pull request merged**
