### PR TITLE
bug 1888223: remove priority from protected data access request link

### PR DESCRIPTION
**Pull request by willkg**
To test, do this:

1. build socorro and then `make run`
2. go to http://localhost:8000/documentation/protected_data_access/
3. click on link to request protected data access
4. make sure the priority isn't set to `P3`--it should be `--`

### CODE REVIEW

**Comment by smarnach** [comment]
I tried following the testing instructions, but I was held up by this typo in the Makefile: https://github.com/mozilla-services/socorro/pull/6564

**Review by biancadanforth — APPROVED** [review]
R+ once the typo from #6564 was fixed it worked for me.

**Review by smarnach — APPROVED** [review]
I followed the test instructions, and on the "New bug" page in Bugzilla I get to when clicking the link there isn't any priority field. So I can't really verify that it's set to "--" since it's just not there. But the priority is definitly gone from the query parameters, so I guess it's fine.

**Comment by willkg** [comment]
Thank you both for reviewing and fixing that `make run` issue!

**Pull request merged**
