### PR TITLE
fixes bug 1231672 - Delete explosiveness table

### PR DESCRIPTION
**Pull request by peterbe**
For some reason the `Explosiveness` class in `models.py` [was removed](https://bugzilla.mozilla.org/show_bug.cgi?id=1231672#c2) but no alembic migration was made for deleting the actual table.

### CODE REVIEW

**Comment by willkg** [comment]
What's creating the explosiveness table? I ask because I don't see anything that creates it, so shouldn't this migration fail on a fresh database?

**Comment by peterbe** [comment]
Excellent question. It's not the first time we do this. I.e. delete things from `models.py` and add alembic scripts that drops tables. Do we not create the postgres tables from alembic migrations then?!

**Comment by willkg** [comment]
I don't see it created in the migrations, either. That's why I'm asking. So it's not created in code and not created by migrations.

When this migration runs and tries to remove a table that doesn't exist, is alembic ok with that? Why does that work?

**Comment by willkg** [comment]
So, turns out nothing creates it and the statement fails:

```
app@d7e499e96dcb:/app$ alembic -c /app/docker/config/alembic.ini upgrade heads
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade e5a31e87d305 -> 77395783fce5, remove explosiveness remnants
Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 11, in <module>
    load_entry_point('alembic==0.8.4', 'console_scripts', 'alembic')()
  File "/usr/local/lib/python2.7/site-packages/alembic/config.py", line 471, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python2.7/site-packages/alembic/config.py", line 465, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python2.7/site-packages/alembic/config.py", line 448, in run_cmd
    **dict((k, getattr(options, k)) for k in kwarg)
  File "/usr/local/lib/python2.7/site-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/usr/local/lib/python2.7/site-packages/alembic/script/base.py", line 397, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "alembic/env.py", line 91, in <module>
    run_migrations_online()
  File "alembic/env.py", line 84, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python2.7/site-packages/alembic/runtime/environment.py", line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 312, in run_migrations
    step.migration_fn(**kw)
  File "/app/alembic/versions/77395783fce5_remove_explosiveness_remnants.py", line 19, in upgrade
    op.drop_table('explosiveness')
  File "<string>", line 8, in drop_table
  File "<string>", line 3, in drop_table
  File "/usr/local/lib/python2.7/site-packages/alembic/operations/ops.py", line 1165, in drop_table
    operations.invoke(op)
  File "/usr/local/lib/python2.7/site-packages/alembic/operations/base.py", line 318, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python2.7/site-packages/alembic/operations/toimpl.py", line 70, in drop_table
    operation.to_table(operations.migration_context)
  File "/usr/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 203, in drop_table
    self._exec(schema.DropTable(table))
  File "/usr/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 69, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 783, in _execute_ddl
    compiled
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (ProgrammingError) table "explosiveness" does not exist
 '\nDROP TABLE explosiveness' {}
```

For local dev environments, we can just wipe them and continue. Both of our server environments probably already have the explosiveness table. Thus I don't think this bites us now. However, I'm concerned we're writing migrations that depend on state that may or may not exist and this will bite us in the future. I'm not sure what to do about that.

**Comment by willkg** [comment]
@peterbe and I talked about this. I think it behooves us to check-then-delete since there's no corresponding create-table operation in past migrations for the drop-table operations we're doing.

So, I suggested doing a try/except, but that's a little gross. @peterbe suggested writing an "if-table-exists" function, but I wasn't sure how to do that offhand. Then @peterbe suggested we just use raw sql and do "drop table if exists" kind of thing.

I think using raw sql here is fine because Socorro will only ever use postgres. He's going to look at what the drop table operation does to make sure that's ok.

**Comment by peterbe** [comment]
@willkg See latest commit. Worked for me locally in docker. Let's see if Travis likes it.

**Comment by willkg** [comment]
This works better for me. No errors now. Thank you!

**Pull request merged**
