### PR TITLE
fix bug 1505954: Add core::panicking::panic_bounds_check to the setinel list

### PR DESCRIPTION
**Pull request by jrmuizel**

### CODE REVIEW

**Comment by willkg** [comment]
Running this through signature generation gives us this:

```
app@socorro:/app$ socorro-cmd signature f6ee9128-a2a5-4e5d-a634-5e61c0181108
Crash id: f6ee9128-a2a5-4e5d-a634-5e61c0181108
Original: mozalloc_abort | abort | __rust_start_panic | rust_begin_unwind
New:      webrender::clip_scroll_tree::ClipScrollTree::get_relative_transform
Same?:    False
```

That looks good to me. I think that's what we want here.

**Comment by willkg** [comment]
Another place where `rust_begin_unwind` shows up is just before `core::panicking::panic_fmt` like these two crashes:

* https://crash-stats.mozilla.com/report/index/fb67472e-c74e-488b-ab5a-f8ba40181113
* https://crash-stats.mozilla.com/report/index/4d82ac7c-e865-498d-b417-2e9590181112

I'm inclined to add `core::panicking::panic_fmt` to the sentinel list, too.

Does that sound ok?

**Comment by jrmuizel** [comment]
Sure.

**Comment by willkg** [comment]
With the above change, signature generation gets us this:

```
app@socorro:/app$ socorro-cmd signature f6ee9128-a2a5-4e5d-a634-5e61c0181108
Crash id: f6ee9128-a2a5-4e5d-a634-5e61c0181108
Original: mozalloc_abort | abort | __rust_start_panic | rust_begin_unwind
New:      webrender::clip_scroll_tree::ClipScrollTree::get_relative_transform
Same?:    False
app@socorro:/app$ socorro-cmd signature f6ee9128-a2a5-4e5d-a634-5e61c0181108 fb67472e-c74e-488b-ab5a-f8ba40181113 4d82ac7c-e865-498d-b417-2e9590181112
Crash id: f6ee9128-a2a5-4e5d-a634-5e61c0181108
Original: mozalloc_abort | abort | __rust_start_panic | rust_begin_unwind
New:      webrender::clip_scroll_tree::ClipScrollTree::get_relative_transform
Same?:    False
Crash id: fb67472e-c74e-488b-ab5a-f8ba40181113
Original: mozalloc_abort | abort | icudt51l.dat@0xe0e463
New:      core::result::unwrap_failed
Same?:    False
Crash id: 4d82ac7c-e865-498d-b417-2e9590181112
Original: mozalloc_abort | __rust_start_panic | rust_begin_unwind
New:      core::option::expect_failed | Servo_Element_IsDisplayNone
Same?:    False
```

That seems better. We can improve further in different bugs.

**Comment by willkg** [comment]
Thank you!

**Pull request merged**
