### PR TITLE
Fixes bug 1368726 - Fix perms for data container

### PR DESCRIPTION
**Pull request by willkg**
This fixes creation of the data container so that the files and directories have
the correct permissions so that the tests can run (and possibly fail) and
everything works right.

### CODE REVIEW

**Comment by willkg** [comment]
@adngdb See if this works for you.

**Comment by adngdb** [comment]
The permission issue is resolved with this, but I still get a lot of errors like this, preventing the tests from running: https://pastebin.mozilla.org/9023170

I assume it is unrelated, if so, r+ on this.

**Comment by willkg** [comment]
Those errors are coming from running tests on your host computer. They shouldn't have been affected by running the tests in the docker environment with "make dockertest" since that doesn't touch your host machine. I'm not sure where those python cache files are coming from.

Maybe try setting:

```
PYTHONDONTWRITEBYTECODE=1
```

in your environment?

**Comment by willkg** [comment]
I pushed another tweak to norecursedirs, though I'm skeptical it'll do anything.

Regardless, I'll wait until CI passes and then land this.

**Pull request merged**
