### PR TITLE
Bug 1675245 - remove ceiling for macOS version (<11) to prevent pretty name 'OS X Unknown'

### PR DESCRIPTION
**Pull request by Archaeopteryx**

### CODE REVIEW

**Review by willkg — CHANGES_REQUESTED** [review]
Once the tests are fixed, this looks good. Thank you for doing it!

**Comment by willkg** [comment]
Tests failed, but for an intermittent issue, so I restarted them.

**Comment by Archaeopteryx** [comment]
@willkg Thanks, test has been updated. Circle CI returns an internal server error now (even after several attempts).

**Review by willkg — APPROVED** [review]

**Comment by willkg** [comment]
Thank you!

**Pull request merged**
