### PR TITLE
Socorro Updates, May 2019

### PR DESCRIPTION
**Pull request by jwhitlock**
Lots of requirements updates, some from PR #4920, plus some other changes. I expect this goes too far, and I can remove some changes.

I noticed some errors from ``pip`` about package version being outside of the requested range of the package that requests them. I downgraded some packages to make ``pip`` happy:

* ``rsa`` 4.0 to 3.4.2 - The latest version supported by ``aws-cli``
* ``jsonschema`` 3.0.1 to 2.6.1 - New requirement ``aws-sam-translator`` requires ``~=2.6``

Updates in the main ``requirements/default.txt`` and ``constraints.txt``:

* ``psycopg2`` 2.8 → 2.8.2: Fix, including concurrency fix in binary package
* ``Jinja2`` 2.10 → 2.10.1: Security fix for str.format_map
* ``Django`` 2.2 → 2.2.1: psycopg2 2.8 compat, fix regressions
* ``requests-mock`` 1.5.2 -> 1.6.0: Pickling fix, PEP8
* ``pytest`` 4.4.0 → 4.4.1: Bug fixes
* ``mozilla-django-oidc`` 1.2.1 → 1.2.2: Code of Conduct, settings overrides
* ``urllib3`` 1.24.1 → 1.24.3: Fixes for CA cert handling
* ``aws-cli`` 1.16.122 → 1.16.154: Updates for API changes
* ``moto`` 1.3.7 → 1.3.8: 6 months of changes, no changelog
* ``botocore`` 1.12.112 → 1.12.144: Updates for API changes
* ``jsondiff`` 1.1.1 → 1.1.2: Documentation, minor changes

New dependencies:

* ``aws-sam-translator`` 1.11.0: Dependency of cfn-lint
* ``cfn-lint`` 0.19.1: Dependency of moto 1.3.8
* ``jsonpatch`` 1.23: Dependency of cfn-lint
* ``jsonpointer`` 2.0: Dependency of jsonpatch

Updates in ``docs/requirements.txt``:

* ``Sphinx`` 1.8.3 → 2.0.1: Drop Python 2.7, many deprecations
* ``sphinx_rtd_theme`` 0.4.2 → 0.4.3: New format for definition lists
* ``packaging`` 18.0 → 19.0: Fixes for file and direct URL reqs
* ``pyparsing`` 2.3.0 → 2.4.0: API change in handling AND tokens
* ``Jinja2`` 2.10 → 2.10.1: Safer handling of str.format_map
* ``pytz`` 2018.7 → 2019.1: Latest timezone database
* ``urllib3`` 1.24.1 → 1.24.3: Better validation of CA certificates
* ``certifi`` 2018.11.29 → 2019.3.9: Latest set of certificates
* ``MarkupSafe`` 1.1.0 → 1.1.1: Fix error handling from C code
* ``recommonmark`` 0.4.0 → 0.5.0: Various fixes, no changelog
* ``CommonMark`` 0.5.4 → 0.9.0: PEP8 module name, CommonMark 0.29

New doc dependencies from Sphinx 2.0:

* ``sphinxcontrib-devhelp`` 1.0.1
* ``sphinxcontrib-htmlhelp`` 1.0.2
* ``sphinxcontrib-jsmath`` 1.0.1
* ``sphinxcontrib-qthelp`` 1.0.2
* ``sphinxcontrib-serializinghtml`` 1.1.3

Other changes:
- I'm asking pyup to suggest security updates in ``requirements/constraints.txt``.
- Changes to ``docs/conf.py`` for PEP8, to remove a warning, and bump copyright.

My local tests were mostly poking around with ``pipdeptree``, and running ``make build build-docs docs test lint``.

### CODE REVIEW

**Comment by jwhitlock** [comment]
It appears that ``rsa`` and ``PyYAML`` will probably work with ``aws-cli``, but the maintainers are not updating the requirements range because the latest versions of those packages do not support Python 2.6, which is a requirement for ``aws-cli``, possibly to support RHEL 6. We could update and ignore the warnings, or continue using older versions.

**Comment by willkg** [comment]
I'm getting this when doing a `make build`:

```
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    cfn-lint from https://files.pythonhosted.org/packages/dd/82/f3c539fb6db5776b49138a8d9212a99313172d701b11e05824d224590483/cfn_lint-0.19.1-py3-none-any.whl#sha256=1bd2a71eca128f5cb1c6770d32668294cf6d91dc78dc80f4ecb4f041e2abd3d8 (from moto==1.3.8->-r requirements/default.txt (line 172))
```

Any idea what I might be doing wrong?

As an aside, you can do:

```
$ NOCACHE=1 make build
```

and get a fresh build that doesn't use Docker caching. I don't think that helps you here much, but figured I'd mention it because it's helpful sometimes.

**Comment by jwhitlock** [comment]
I don't get this error with ``NOCACHE=1 make build``. Here's the download line for me:

```
Collecting cfn-lint==0.19.1 (from -c requirements/constraints.txt (line 464))
  Downloading https://files.pythonhosted.org/packages/dd/82/f3c539fb6db5776b49138a8d9212a99313172d701b11e05824d224590483/cfn_lint-0.19.1-py3-none-any.whl (2.1MB)
```

That sha256 hash ``5a723ff791fc`` is the one in ``requirements/constraints.txt``.

**Comment by willkg** [comment]
Bah--my fault. I was looking at PR 4920.

**Pull request merged**
