### PR TITLE
Set number of pytest processes via environment variable

### PR DESCRIPTION
**Pull request by stephendonner**
@chartjes / @davehunt r?  @willkg mind holding off on a merge until @davehunt or I give the "all clear?"  We're migrating to (and still configuring) new Jenkins instances - thanks!

Passing-build output: https://gist.github.com/stephendonner/8e36e42f6de51067e98a700f6b2d9b20

### CODE REVIEW

**Comment by willkg** [comment]
Can do!

**Comment by davehunt** [comment]
r+ This can be merged after [bug 1410925](https://bugzilla.mozilla.org/show_bug.cgi?id=1410925) is resolved.

**Comment by chartjes** [comment]
@stephendonner @davehunt 👍

**Comment by stephendonner** [comment]
@willkg - https://bugzilla.mozilla.org/show_bug.cgi?id=1410925 is fixed (and I'll verify post-merge); this can be merged any time you have a moment, now - thanks!

**Comment by willkg** [comment]
Thank you!

**Pull request merged**
