### PR TITLE
bug 1468763: remove "docker" prefixes from make rules

### PR DESCRIPTION
**Pull request by willkg**
Dropping the "docker" in the "dockerbuild" rule.

### CODE REVIEW

**Comment by AlexisDeschamps** [comment]
Wouldn't you want to change the other commands starting with `docker` as well to match?

**Comment by willkg** [comment]
Yes! You're right on--there's a bunch of other things to do. I'll do those now.

**Comment by willkg** [comment]
@AlexisDeschamps Can you review this?

**Comment by AlexisDeschamps** [comment]
Seems good. Tried locally and seems to work great.
Question: why not change the `Python 3 transition related things` commands as well?
Suggestion: change the PR title to be more general.

**Comment by willkg** [comment]
I was thinking the Python3 stuff is temporary and it's easier to just leave it as is and then it goes away in a few months.

Changing the PR title is a good idea. I'll do that now.

**Pull request merged**
