### PR TITLE
bug 1626245 - Surface Linux LSB release information provided in the format used by Debian/Fedora

### PR DESCRIPTION
**Pull request by gabrielesvelto**

### CODE REVIEW

**Comment by willkg** [comment]
We have to manually test minidump-stackwalk changes since we don't have any automated testing set up around it. Do we have crash reports we can test this out on?

**Comment by gabrielesvelto** [comment]
Yes, [this](https://crash-stats.mozilla.com/report/index/96d830c7-a18e-485d-ab2a-3b8b60200407) is a Fedora crash, the four fields should be:

id: "fedora"
version: "32"
codename: ""
description: "Fedora 32 (Workstation Edition)"

[This](https://crash-stats.mozilla.com/report/index/49226eee-029f-4545-a527-b2c470200402) one is Ubuntu and should give:

id: "Ubuntu"
release: "19.04"
codename: "disco"
description: "Ubuntu 19.04"

Finally [this](https://crash-stats.mozilla.com/report/index/413034a9-dc7a-46d9-bdbb-6fb1d0200407) one is Debian and should give:
id: "debian"
release: "8"
codename: ""
description: "Debian GNU/Linux 8 (jessie)"

**Comment by willkg** [comment]
@gabrielesvelto I had to fix one of the scripts that I need to test this. We're going to need to rebase against master tip anyhow. Can you rebase it now and then I'll test it out and make sure I don't make other changes until this lands so we don't have to rebase again?

**Comment by gabrielesvelto** [comment]
Will do!

**Comment by willkg** [comment]
For 96d830c7-a18e-485d-ab2a-3b8b60200407, without the changes, I see `lsb_release` as this:

```
{}
```

With changes, I see this:

```
{
  "codename": "\"\"",
  "description": "Fedora 32 (Workstation Edition)",
  "id": "fedora",
  "release": "32"
}
```

Does that last one look right? Looks like a string with `""` in it and not just an empty string.

**Comment by willkg** [comment]
As a side note, I'm testing this way:

```
$ make build
$ make shell
app@socorro:/app$ ./scripts/run_mdsw.sh 96d830c7-a18e-485d-ab2a-3b8b60200407 > out.json
```

Then doing this in another shell:

```
$ jq '.lsb_release' out.json
```

**Comment by gabrielesvelto** [comment]
The codename string is odd, I'll double-check it.

**Comment by gabrielesvelto** [comment]
I pushed a fix that will solve the weird codename, leaving an empty string instead of the double double quotes.

**Comment by willkg** [comment]
With that last fix, I'm getting this:

```
96d830c7-a18e-485d-ab2a-3b8b60200407:
{
  "codename": "",
  "description": "Fedora 32 (Workstation Edition)",
  "id": "fedora",
  "release": "32"
}

49226eee-029f-4545-a527-b2c470200402:
null

413034a9-dc7a-46d9-bdbb-6fb1d0200407:
{
  "description": "Debian GNU/Linux 8 (jessie)",
  "id": "debian",
  "release": "8"
}
```

I think that Ubuntu crash report isn't from Ubuntu. Here's one that's showing a platform pretty version that suggests it's Ubuntu:

```
88a21651-ad56-4992-b7c8-2d0130200408:
{
  "codename": "bionic",
  "description": "Ubuntu 18.04.4 LTS",
  "id": "Ubuntu",
  "release": "18.04"
}
```

@gabrielesvelto Does that look right?
```

**Comment by willkg** [comment]
I talked with Gabriele and he said this was super!

**Pull request merged**
